In [ ]:
ls

In [1]:
import os
import pandas as pd

In [2]:
def read_and_clean_data(file_path):
    df = pd.read_csv(file_path)
    df.dropna(inplace=True)
    df['Date'] = pd.to_datetime(df['Date'])
    
    return df

In [145]:
import pandas as pd

def format_merged_df(merged_df, pollutant):
    aqs_parameter_desc = merged_df.iloc[0]['AQS_PARAMETER_DESC']

    county_point_data = merged_df.groupby(['STATE', 'COUNTY', 'Site ID','SITE_LATITUDE', 'SITE_LONGITUDE']).agg({
        'DAILY_AQI_VALUE': ['mean', 'min', 'max']}).reset_index()

    county_point_data.columns = [ 'STATE', 'COUNTY','Site ID', 'SITE_LATITUDE', 'SITE_LONGITUDE', 'Mean_AQI', 'Min_AQI', 'Max_AQI']

    county_point_data['Mean_AQI'] = county_point_data['Mean_AQI'].round().astype(int)
    county_point_data['AQS_PARAMETER_DESC'] = aqs_parameter_desc
    
    if pollutant == 'CO':
        county_point_data.columns = ['STATE','COUNTY', 'Site ID', 'SITE_LATITUDE', 'SITE_LONGITUDE', 'Mean_CO_AQI', 'Min_CO_AQI', 'Max_CO_AQI', 'AQS_PARAMETER_DESC']
    elif pollutant == 'SO2':
        county_point_data.columns = ['STATE', 'COUNTY', 'Site ID', 'SITE_LATITUDE', 'SITE_LONGITUDE', 'Mean_SO2_AQI', 'Min_SO2_AQI', 'Max_SO2_AQI', 'AQS_PARAMETER_DESC']
    elif pollutant == 'NO2':
        county_point_data.columns = ['STATE', 'COUNTY', 'Site ID', 'SITE_LATITUDE', 'SITE_LONGITUDE', 'Mean_NO2_AQI', 'Min_NO2_AQI', 'Max_NO2_AQI', 'AQS_PARAMETER_DESC']
    elif pollutant == 'PM10':
        county_point_data.columns = ['STATE', 'COUNTY', 'Site ID', 'SITE_LATITUDE', 'SITE_LONGITUDE', 'Mean_PM10_AQI', 'Min_PM10_AQI', 'Max_PM10_AQI', 'AQS_PARAMETER_DESC']
    elif pollutant == 'PM2.5':
        county_point_data.columns = ['STATE', 'COUNTY', 'Site ID', 'SITE_LATITUDE', 'SITE_LONGITUDE', 'Mean_PM2.5_AQI', 'Min_PM2.5_AQI', 'Max_PM2.5_AQI', 'AQS_PARAMETER_DESC']
    county_point_data = county_point_data.sort_values(by=['STATE','COUNTY'])
    county_point_data.reset_index(drop=True, inplace=True)
    county_point_df = pd.DataFrame(county_point_data)
    return county_point_df

# Data Processing for CO

In [146]:
co_folder_path = 'CO/'

co_cleaned_dfs = []

for file_name in os.listdir(co_folder_path):
    if file_name.endswith('.csv'):
        file_path = os.path.join(co_folder_path, file_name)
        cleaned_df = read_and_clean_data(file_path)
        co_cleaned_dfs.append(cleaned_df)

In [147]:
co_merged_df = pd.concat(co_cleaned_dfs, ignore_index=True)

In [148]:
co_merged_df

,Date,Source,Site ID,POC,Daily Max 8-hour CO Concentration,UNITS,DAILY_AQI_VALUE,Site Name,DAILY_OBS_COUNT,PERCENT_COMPLETE,AQS_PARAMETER_CODE,AQS_PARAMETER_DESC,CBSA_CODE,CBSA_NAME,STATE_CODE,STATE,COUNTY_CODE,COUNTY,SITE_LATITUDE,SITE_LONGITUDE
0,2021-01-01,AQS,10730023,2,0.2,ppm,2,North Birmingham,19,79.0,42101,Carbon monoxide,13820.0,"Birmingham-Hoover, AL",1,Alabama,73,Jefferson,33.553056,-86.815000
1,2021-01-02,AQS,10730023,2,0.2,ppm,2,North Birmingham,24,100.0,42101,Carbon monoxide,13820.0,"Birmingham-Hoover, AL",1,Alabama,73,Jefferson,33.553056,-86.815000
2,2021-01-03,AQS,10730023,2,0.5,ppm,6,North Birmingham,24,100.0,42101,Carbon monoxide,13820.0,"Birmingham-Hoover, AL",1,Alabama,73,Jefferson,33.553056,-86.815000
3,2021-01-04,AQS,10730023,2,0.6,ppm,7,North Birmingham,24,100.0,42101,Carbon monoxide,13820.0,"Birmingham-Hoover, AL",1,Alabama,73,Jefferson,33.553056,-86.815000
4,2021-01-05,AQS,10730023,2,0.4,ppm,5,North Birmingham,18,75.0,42101,Carbon monoxide,13820.0,"Birmingham-Hoover, AL",1,Alabama,73,Jefferson,33.553056,-86.815000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85699,2021-12-27,AQS,560391013,1,0.1,ppm,1,Yellowstone National Park - Old Faithful Snow ...,24,100.0,42101,Carbon monoxide,27220.0,"Jackson, WY-ID",56,Wyoming,39,Teton,44.373056,-110.830833
85700,2021-12-28,AQS,560391013,1,0.1,ppm,1,Yellowstone National Park - Old Faithful Snow ...,24,100.0,42101,Carbon monoxide,27220.0,"Jackson, WY-ID",56,Wyoming,39,Teton,44.373056,-110.830833
85701,2021-12-29,AQS,560391013,1,0.1,ppm,1,Yellowstone National Park - Old Faithful Snow ...,24,100.0,42101,Carbon monoxide,27220.0,"Jackson, WY-ID",56,Wyoming,39,Teton,44.373056,-110.830833
85702,2021-12-30,AQS,560391013,1,0.1,ppm,1,Yellowstone National Park - Old Faithful Snow ...,24,100.0,42101,Carbon monoxide,27220.0,"Jackson, WY-ID",56,Wyoming,39,Teton,44.373056,-110.830833
85703,2021-12-31,AQS,560391013,1,0.1,ppm,1,Yellowstone National Park - Old Faithful Snow ...,24,100.0,42101,Carbon monoxide,27220.0,"Jackson, WY-ID",56,Wyoming,39,Teton,44.373056,-110.830833

In [149]:
co_df = format_merged_df(co_merged_df, 'CO')
co_df

,STATE,COUNTY,Site ID,SITE_LATITUDE,SITE_LONGITUDE,Mean_CO_AQI,Min_CO_AQI,Max_CO_AQI,AQS_PARAMETER_DESC
0,Alabama,Jefferson,10730023,33.553056,-86.815000,4,1,11,Carbon monoxide
1,Alabama,Jefferson,10731003,33.485556,-86.915000,4,0,14,Carbon monoxide
2,Alabama,Jefferson,10732059,33.521427,-86.844112,6,1,14,Carbon monoxide
3,Alaska,Anchorage,20200018,61.205861,-149.824602,6,1,25,Carbon monoxide
4,Alaska,Fairbanks North Star,20900034,64.845690,-147.727413,5,0,20,Carbon monoxide
...,...,...,...,...,...,...,...,...,...
252,Wisconsin,Dodge,550270001,43.466110,-88.621110,2,0,6,Carbon monoxide
253,Wisconsin,Kenosha,550590019,42.504720,-87.809300,2,1,5,Carbon monoxide
254,Wisconsin,Milwaukee,550790056,42.932570,-87.934340,4,1,10,Carbon monoxide
255,Wyoming,Laramie,560210100,41.182227,-104.778334,1,0,3,Carbon monoxide
256,Wyoming,Teton,560391013,44.373056,-110.830833,1,1,7,Carbon monoxide

In [150]:
co_df.to_csv('cleaned_CO_data.csv', index=False)

# **Data Processing for NO2**

In [151]:
No2_folder_path = 'NO2/'

No2_cleaned_dfs = []

for file_name in os.listdir(No2_folder_path):
    if file_name.endswith('.csv'):
        file_path = os.path.join(No2_folder_path, file_name)
        cleaned_df = read_and_clean_data(file_path)
        No2_cleaned_dfs.append(cleaned_df)

In [152]:
No2_merged_df = pd.concat(No2_cleaned_dfs, ignore_index=True)
No2_merged_df

,Date,Source,Site ID,POC,Daily Max 1-hour NO2 Concentration,UNITS,DAILY_AQI_VALUE,Site Name,DAILY_OBS_COUNT,PERCENT_COMPLETE,AQS_PARAMETER_CODE,AQS_PARAMETER_DESC,CBSA_CODE,CBSA_NAME,STATE_CODE,STATE,COUNTY_CODE,COUNTY,SITE_LATITUDE,SITE_LONGITUDE
0,2021-01-01,AQS,10730023,1,23.2,ppb,22,North Birmingham,24,100.0,42602,Nitrogen dioxide (NO2),13820.0,"Birmingham-Hoover, AL",1,Alabama,73,Jefferson,33.553056,-86.815000
1,2021-01-02,AQS,10730023,1,9.8,ppb,8,North Birmingham,24,100.0,42602,Nitrogen dioxide (NO2),13820.0,"Birmingham-Hoover, AL",1,Alabama,73,Jefferson,33.553056,-86.815000
2,2021-01-03,AQS,10730023,1,29.7,ppb,27,North Birmingham,24,100.0,42602,Nitrogen dioxide (NO2),13820.0,"Birmingham-Hoover, AL",1,Alabama,73,Jefferson,33.553056,-86.815000
3,2021-01-04,AQS,10730023,1,27.9,ppb,25,North Birmingham,24,100.0,42602,Nitrogen dioxide (NO2),13820.0,"Birmingham-Hoover, AL",1,Alabama,73,Jefferson,33.553056,-86.815000
4,2021-01-05,AQS,10730023,1,31.5,ppb,29,North Birmingham,21,88.0,42602,Nitrogen dioxide (NO2),13820.0,"Birmingham-Hoover, AL",1,Alabama,73,Jefferson,33.553056,-86.815000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
140100,2021-12-27,AQS,560391013,1,2.0,ppb,2,Yellowstone National Park - Old Faithful Snow ...,22,92.0,42602,Nitrogen dioxide (NO2),27220.0,"Jackson, WY-ID",56,Wyoming,39,Teton,44.373056,-110.830833
140101,2021-12-28,AQS,560391013,1,2.3,ppb,2,Yellowstone National Park - Old Faithful Snow ...,24,100.0,42602,Nitrogen dioxide (NO2),27220.0,"Jackson, WY-ID",56,Wyoming,39,Teton,44.373056,-110.830833
140102,2021-12-29,AQS,560391013,1,2.5,ppb,2,Yellowstone National Park - Old Faithful Snow ...,24,100.0,42602,Nitrogen dioxide (NO2),27220.0,"Jackson, WY-ID",56,Wyoming,39,Teton,44.373056,-110.830833
140103,2021-12-30,AQS,560391013,1,2.4,ppb,2,Yellowstone National Park - Old Faithful Snow ...,22,92.0,42602,Nitrogen dioxide (NO2),27220.0,"Jackson, WY-ID",56,Wyoming,39,Teton,44.373056,-110.830833
140104,2021-12-31,AQS,560391013,1,2.9,ppb,2,Yellowstone National Park - Old Faithful Snow ...,24,100.0,42602,Nitrogen dioxide (NO2),27220.0,"Jackson, WY-ID",56,Wyoming,39,Teton,44.373056,-110.830833

In [153]:
No2_df = format_merged_df(No2_merged_df, 'NO2')
No2_df

,STATE,COUNTY,Site ID,SITE_LATITUDE,SITE_LONGITUDE,Mean_NO2_AQI,Min_NO2_AQI,Max_NO2_AQI,AQS_PARAMETER_DESC
0,Alabama,Jefferson,10730023,33.553056,-86.815000,18,3,42,Nitrogen dioxide (NO2)
1,Alabama,Jefferson,10732059,33.521427,-86.844112,20,5,47,Nitrogen dioxide (NO2)
2,Arizona,Maricopa,40130019,33.483780,-112.142560,29,7,52,Nitrogen dioxide (NO2)
3,Arizona,Maricopa,40133002,33.457970,-112.046590,32,6,57,Nitrogen dioxide (NO2)
4,Arizona,Maricopa,40134011,33.369850,-112.620680,17,4,38,Nitrogen dioxide (NO2)
...,...,...,...,...,...,...,...,...,...
412,Wyoming,Sweetwater,560370023,41.556430,-109.530440,16,1,32,Nitrogen dioxide (NO2)
413,Wyoming,Sweetwater,560370025,41.905400,-109.850000,3,1,8,Nitrogen dioxide (NO2)
414,Wyoming,Sweetwater,560370200,41.677667,-108.024835,9,0,39,Nitrogen dioxide (NO2)
415,Wyoming,Sweetwater,560370300,41.750556,-109.788333,3,0,18,Nitrogen dioxide (NO2)
416,Wyoming,Teton,560391013,44.373056,-110.830833,3,0,35,Nitrogen dioxide (NO2)

In [154]:
No2_df.to_csv('cleaned_NO2_data.csv', index=False)

# Data Processing for PM2.5

In [155]:
PM2_5_folder_path = 'PM2.5/'
PM2_5_cleaned_dfs = []

for file_name in os.listdir(PM2_5_folder_path):
    if file_name.endswith('.csv'):
        file_path = os.path.join(PM2_5_folder_path, file_name)
        cleaned_df = read_and_clean_data(file_path)
        PM2_5_cleaned_dfs.append(cleaned_df)

In [156]:
PM2_5_merged_df = pd.concat(PM2_5_cleaned_dfs, ignore_index=True)
PM2_5_merged_df

,Date,Source,Site ID,POC,Daily Mean PM2.5 Concentration,UNITS,DAILY_AQI_VALUE,Site Name,DAILY_OBS_COUNT,PERCENT_COMPLETE,AQS_PARAMETER_CODE,AQS_PARAMETER_DESC,CBSA_CODE,CBSA_NAME,STATE_CODE,STATE,COUNTY_CODE,COUNTY,SITE_LATITUDE,SITE_LONGITUDE
0,2021-01-01,AQS,10030010.0,1.0,6.4,ug/m3 LC,27.0,"FAIRHOPE, Alabama",1.0,100.0,88101.0,PM2.5 - Local Conditions,19300.0,"Daphne-Fairhope-Foley, AL",1.0,Alabama,3.0,Baldwin,30.497478,-87.880258
1,2021-01-07,AQS,10030010.0,1.0,5.7,ug/m3 LC,24.0,"FAIRHOPE, Alabama",1.0,100.0,88101.0,PM2.5 - Local Conditions,19300.0,"Daphne-Fairhope-Foley, AL",1.0,Alabama,3.0,Baldwin,30.497478,-87.880258
2,2021-01-13,AQS,10030010.0,1.0,11.0,ug/m3 LC,46.0,"FAIRHOPE, Alabama",1.0,100.0,88101.0,PM2.5 - Local Conditions,19300.0,"Daphne-Fairhope-Foley, AL",1.0,Alabama,3.0,Baldwin,30.497478,-87.880258
3,2021-01-16,AQS,10030010.0,1.0,5.1,ug/m3 LC,21.0,"FAIRHOPE, Alabama",1.0,100.0,88101.0,PM2.5 - Local Conditions,19300.0,"Daphne-Fairhope-Foley, AL",1.0,Alabama,3.0,Baldwin,30.497478,-87.880258
4,2021-01-19,AQS,10030010.0,1.0,12.7,ug/m3 LC,52.0,"FAIRHOPE, Alabama",1.0,100.0,88101.0,PM2.5 - Local Conditions,19300.0,"Daphne-Fairhope-Foley, AL",1.0,Alabama,3.0,Baldwin,30.497478,-87.880258
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
383968,2021-12-27,AQS,560391013.0,1.0,2.2,ug/m3 LC,9.0,Yellowstone National Park - Old Faithful Snow ...,1.0,100.0,88101.0,PM2.5 - Local Conditions,27220.0,"Jackson, WY-ID",56.0,Wyoming,39.0,Teton,44.373056,-110.830833
383969,2021-12-28,AQS,560391013.0,1.0,2.5,ug/m3 LC,10.0,Yellowstone National Park - Old Faithful Snow ...,1.0,100.0,88101.0,PM2.5 - Local Conditions,27220.0,"Jackson, WY-ID",56.0,Wyoming,39.0,Teton,44.373056,-110.830833
383970,2021-12-29,AQS,560391013.0,1.0,1.5,ug/m3 LC,6.0,Yellowstone National Park - Old Faithful Snow ...,1.0,100.0,88101.0,PM2.5 - Local Conditions,27220.0,"Jackson, WY-ID",56.0,Wyoming,39.0,Teton,44.373056,-110.830833
383971,2021-12-30,AQS,560391013.0,1.0,1.5,ug/m3 LC,6.0,Yellowstone National Park - Old Faithful Snow ...,1.0,100.0,88101.0,PM2.5 - Local Conditions,27220.0,"Jackson, WY-ID",56.0,Wyoming,39.0,Teton,44.373056,-110.830833
383972,2021-12-31,AQS,560391013.0,1.0,3.4,ug/m3 LC,14.0,Yellowstone National Park - Old Faithful Snow ...,1.0,100.0,88101.0,PM2.5 - Local Conditions,27220.0,"Jackson, WY-ID",56.0,Wyoming,39.0,Teton,44.373056,-110.830833

In [157]:
PM2_5_df = format_merged_df(PM2_5_merged_df, 'PM2.5')
PM2_5_df

,STATE,COUNTY,Site ID,SITE_LATITUDE,SITE_LONGITUDE,Mean_PM2.5_AQI,Min_PM2.5_AQI,Max_PM2.5_AQI,AQS_PARAMETER_DESC
0,Alabama,Baldwin,10030010.0,30.497478,-87.880258,30,10.0,58.0,PM2.5 - Local Conditions
1,Alabama,DeKalb,10491003.0,34.288567,-85.969858,31,10.0,77.0,PM2.5 - Local Conditions
2,Alabama,Etowah,10550010.0,33.988210,-85.992556,34,6.0,77.0,PM2.5 - Local Conditions
3,Alabama,Jefferson,10730023.0,33.553056,-86.815000,35,12.0,75.0,PM2.5 - Local Conditions
4,Alabama,Jefferson,10731005.0,33.331111,-87.003611,35,11.0,80.0,PM2.5 - Local Conditions
...,...,...,...,...,...,...,...,...,...
1086,Wyoming,Sheridan,560331003.0,44.782750,-106.964320,15,9.0,25.0,PM2.5 - Local Conditions
1087,Wyoming,Sweetwater,560370007.0,41.592536,-109.220852,27,2.0,112.0,PM2.5 - Local Conditions
1088,Wyoming,Sweetwater,560370023.0,41.556430,-109.530440,13,2.0,78.0,PM2.5 - Local Conditions
1089,Wyoming,Teton,560391006.0,43.457760,-110.797990,19,0.0,118.0,PM2.5 - Local Conditions
1090,Wyoming,Teton,560391013.0,44.373056,-110.830833,18,0.0,131.0,PM2.5 - Local Conditions

In [158]:
PM2_5_df.to_csv('cleaned_PM2_5_data.csv', index=False)

# Data Processing for PM10

In [159]:
PM10_folder_path = 'PM10/'

In [160]:
PM10_cleaned_dfs = []

for file_name in os.listdir(PM10_folder_path):
    if file_name.endswith('.csv'):
        file_path = os.path.join(PM10_folder_path, file_name)
        cleaned_df = read_and_clean_data(file_path)
        PM10_cleaned_dfs.append(cleaned_df)

In [161]:
PM10_merged_df = pd.concat(PM10_cleaned_dfs, ignore_index=True)
PM10_merged_df

,Date,Source,Site ID,POC,Daily Mean PM10 Concentration,UNITS,DAILY_AQI_VALUE,Site Name,DAILY_OBS_COUNT,PERCENT_COMPLETE,AQS_PARAMETER_CODE,AQS_PARAMETER_DESC,CBSA_CODE,CBSA_NAME,STATE_CODE,STATE,COUNTY_CODE,COUNTY,SITE_LATITUDE,SITE_LONGITUDE
0,2021-01-01,AQS,10730023,4,11,ug/m3 SC,10,North Birmingham,1,100.0,81102,PM10 Total 0-10um STP,13820.0,"Birmingham-Hoover, AL",1,Alabama,73,Jefferson,33.553056,-86.815000
1,2021-01-02,AQS,10730023,4,10,ug/m3 SC,9,North Birmingham,1,100.0,81102,PM10 Total 0-10um STP,13820.0,"Birmingham-Hoover, AL",1,Alabama,73,Jefferson,33.553056,-86.815000
2,2021-01-03,AQS,10730023,4,6,ug/m3 SC,6,North Birmingham,1,100.0,81102,PM10 Total 0-10um STP,13820.0,"Birmingham-Hoover, AL",1,Alabama,73,Jefferson,33.553056,-86.815000
3,2021-01-04,AQS,10730023,4,22,ug/m3 SC,20,North Birmingham,1,100.0,81102,PM10 Total 0-10um STP,13820.0,"Birmingham-Hoover, AL",1,Alabama,73,Jefferson,33.553056,-86.815000
4,2021-01-05,AQS,10730023,4,18,ug/m3 SC,17,North Birmingham,1,100.0,81102,PM10 Total 0-10um STP,13820.0,"Birmingham-Hoover, AL",1,Alabama,73,Jefferson,33.553056,-86.815000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
146207,2021-12-27,AQS,560410201,1,4,ug/m3 SC,4,Haystack Upwind,1,100.0,81102,PM10 Total 0-10um STP,21740.0,"Evanston, WY",56,Wyoming,41,Uinta,41.408699,-110.702153
146208,2021-12-28,AQS,560410201,1,4,ug/m3 SC,4,Haystack Upwind,1,100.0,81102,PM10 Total 0-10um STP,21740.0,"Evanston, WY",56,Wyoming,41,Uinta,41.408699,-110.702153
146209,2021-12-29,AQS,560410201,1,4,ug/m3 SC,4,Haystack Upwind,1,100.0,81102,PM10 Total 0-10um STP,21740.0,"Evanston, WY",56,Wyoming,41,Uinta,41.408699,-110.702153
146210,2021-12-30,AQS,560410201,1,4,ug/m3 SC,4,Haystack Upwind,1,100.0,81102,PM10 Total 0-10um STP,21740.0,"Evanston, WY",56,Wyoming,41,Uinta,41.408699,-110.702153
146211,2021-12-31,AQS,560410201,1,3,ug/m3 SC,3,Haystack Upwind,1,100.0,81102,PM10 Total 0-10um STP,21740.0,"Evanston, WY",56,Wyoming,41,Uinta,41.408699,-110.702153

In [162]:
PM10_df = format_merged_df(PM10_merged_df, 'PM10')
PM10_df

,STATE,COUNTY,Site ID,SITE_LATITUDE,SITE_LONGITUDE,Mean_PM10_AQI,Min_PM10_AQI,Max_PM10_AQI,AQS_PARAMETER_DESC
0,Alabama,Jefferson,10730023,33.553056,-86.815000,21,6,55,PM10 Total 0-10um STP
1,Alabama,Jefferson,10731010,33.545278,-86.549167,13,4,30,PM10 Total 0-10um STP
2,Alabama,Jefferson,10732003,33.499722,-86.924167,17,5,49,PM10 Total 0-10um STP
3,Alabama,Jefferson,10736002,33.578333,-86.773889,19,2,52,PM10 Total 0-10um STP
4,Alabama,Jefferson,10736004,33.565278,-86.796389,20,5,91,PM10 Total 0-10um STP
...,...,...,...,...,...,...,...,...,...
551,Wyoming,Sweetwater,560371414,41.521672,-108.662222,13,0,123,PM10 Total 0-10um STP
552,Wyoming,Sweetwater,560371868,41.647036,-108.632466,16,4,147,PM10 Total 0-10um STP
553,Wyoming,Teton,560391006,43.457760,-110.797990,14,1,81,PM10 Total 0-10um STP
554,Wyoming,Uinta,560410200,41.407517,-110.678433,11,1,60,PM10 Total 0-10um STP
555,Wyoming,Uinta,560410201,41.408699,-110.702153,11,2,60,PM10 Total 0-10um STP

In [163]:
PM10_df.to_csv('cleaned_PM10_data.csv', index=False)

# Data Processing for SO2

In [164]:
So2_folder_path = 'SO2/'

In [165]:
So2_cleaned_dfs = []

for file_name in os.listdir(So2_folder_path):
    if file_name.endswith('.csv'):
        file_path = os.path.join(So2_folder_path, file_name)
        cleaned_df = read_and_clean_data(file_path)
        So2_cleaned_dfs.append(cleaned_df)

In [166]:
So2_merged_df = pd.concat(So2_cleaned_dfs, ignore_index=True)
So2_merged_df

,Date,Source,Site ID,POC,Daily Max 1-hour SO2 Concentration,UNITS,DAILY_AQI_VALUE,Site Name,DAILY_OBS_COUNT,PERCENT_COMPLETE,AQS_PARAMETER_CODE,AQS_PARAMETER_DESC,CBSA_CODE,CBSA_NAME,STATE_CODE,STATE,COUNTY_CODE,COUNTY,SITE_LATITUDE,SITE_LONGITUDE
0,2021-01-01,AQS,10730023,2,0.6,ppb,0,North Birmingham,24,100.0,42401,Sulfur dioxide,13820.0,"Birmingham-Hoover, AL",1,Alabama,73,Jefferson,33.553056,-86.815000
1,2021-01-02,AQS,10730023,2,2.6,ppb,3,North Birmingham,24,100.0,42401,Sulfur dioxide,13820.0,"Birmingham-Hoover, AL",1,Alabama,73,Jefferson,33.553056,-86.815000
2,2021-01-03,AQS,10730023,2,0.5,ppb,0,North Birmingham,24,100.0,42401,Sulfur dioxide,13820.0,"Birmingham-Hoover, AL",1,Alabama,73,Jefferson,33.553056,-86.815000
3,2021-01-04,AQS,10730023,2,3.0,ppb,4,North Birmingham,24,100.0,42401,Sulfur dioxide,13820.0,"Birmingham-Hoover, AL",1,Alabama,73,Jefferson,33.553056,-86.815000
4,2021-01-05,AQS,10730023,2,2.4,ppb,3,North Birmingham,21,88.0,42401,Sulfur dioxide,13820.0,"Birmingham-Hoover, AL",1,Alabama,73,Jefferson,33.553056,-86.815000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
131254,2021-12-27,AQS,560370300,1,0.4,ppb,0,Moxa Arch,24,100.0,42401,Sulfur dioxide,40540.0,"Rock Springs, WY",56,Wyoming,37,Sweetwater,41.750556,-109.788333
131255,2021-12-28,AQS,560370300,1,0.2,ppb,0,Moxa Arch,24,100.0,42401,Sulfur dioxide,40540.0,"Rock Springs, WY",56,Wyoming,37,Sweetwater,41.750556,-109.788333
131256,2021-12-29,AQS,560370300,1,1.1,ppb,1,Moxa Arch,22,92.0,42401,Sulfur dioxide,40540.0,"Rock Springs, WY",56,Wyoming,37,Sweetwater,41.750556,-109.788333
131257,2021-12-30,AQS,560370300,1,0.1,ppb,0,Moxa Arch,24,100.0,42401,Sulfur dioxide,40540.0,"Rock Springs, WY",56,Wyoming,37,Sweetwater,41.750556,-109.788333
131258,2021-12-31,AQS,560370300,1,0.1,ppb,0,Moxa Arch,24,100.0,42401,Sulfur dioxide,40540.0,"Rock Springs, WY",56,Wyoming,37,Sweetwater,41.750556,-109.788333

In [167]:
So2_df = format_merged_df(So2_merged_df, 'SO2')
So2_df

,STATE,COUNTY,Site ID,SITE_LATITUDE,SITE_LONGITUDE,Mean_SO2_AQI,Min_SO2_AQI,Max_SO2_AQI,AQS_PARAMETER_DESC
0,Alabama,Jefferson,10730023,33.553056,-86.815000,2,0,20,Sulfur dioxide
1,Alabama,Jefferson,10731003,33.485556,-86.915000,1,0,13,Sulfur dioxide
2,Alabama,Mobile,10970003,30.770181,-88.087761,2,0,21,Sulfur dioxide
3,Alabama,Shelby,11179001,33.092800,-86.807200,6,0,107,Sulfur dioxide
4,Alaska,Fairbanks North Star,20900034,64.845690,-147.727413,12,0,59,Sulfur dioxide
...,...,...,...,...,...,...,...,...,...
387,Wyoming,Fremont,560130004,43.024210,-108.363700,1,0,17,Sulfur dioxide
388,Wyoming,Laramie,560210100,41.182227,-104.778334,1,0,16,Sulfur dioxide
389,Wyoming,Sweetwater,560370023,41.556430,-109.530440,0,0,29,Sulfur dioxide
390,Wyoming,Sweetwater,560370025,41.905400,-109.850000,1,0,9,Sulfur dioxide
391,Wyoming,Sweetwater,560370300,41.750556,-109.788333,1,0,85,Sulfur dioxide

In [168]:
So2_df.to_csv('cleaned_So2_data.csv', index=False)